---
- name: Check VMware VM Configuration
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Gather VM Information
      community.vmware.vmware_vm_info:
        validate_certs: no
        vm_name: "{{ item }}"
      register: vm_info
      loop: "{{ server.split(',') }}"


    - name: Changing network adapter to {{ vlan }}
      community.vmware.vmware_guest_network:
        #datacenter: "{{ 'daevcsa01.eur.ad.sag' if datacenter == 'dae' else 'vadvc01.eur.ad.sag' if datacenter == 'vad' }}"
        cluster: "{{ item.1.cluster }}"
        validate_certs: no
        name: "{{ item.1.guest_name }}"
        mac_address: "{{ item.1.mac_address[0] }}"
        network_name: "{{ 'VLAN 1000' if vlan == 'SAG DMZ -> IntegrationCo DMZ' else 'VM Network' if vlan == 'SAG Internal -> IntegrationCo Internal' }}"
        state: present
      with_items:
        - "{{ vm_info.results | subelements('virtual_machines') }}"


    - name: Powering off "{{ item }}"
      community.vmware.vmware_guest_powerstate:
        validate_certs: no
        name: "{{ item }}"
        state: powered-off
      loop: "{{ server.split(',') }}"
      
    - name: Custom tags
      community.vmware.vmware_guest_custom_attributes:
        validate_certs: no  
        name: "{{ item }}"
        attributes:
          - name: Company
            value: IntegrationCo
      loop: "{{ server.split(',') }}"




    - name: Powering on "{{ item }}"
      community.vmware.vmware_guest_powerstate:
        validate_certs: no
        name: "{{ item }}"
        state: powered-on
      loop: "{{ server.split(',') }}"
      delegate_to: localhost

