# # Tower automatically installs these collections when project syncs
collections:
  - name: azure.azcollection
  - name: ansible.windows
  - name: community.windows
  - name: community.general
    version: 5.8.0
  - name: community.vmware
  - name: vmware.vmware_rest
    version: 2.2.0
  - name: community.crypto
