---
- name: Check VMware VM Configuration
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Gather VM Information
      community.vmware.vmware_vm_info:
        validate_certs: no
        vm_name: "{{ item }}"
      register: vm_info
      with_items: "{{ server.split(',') }}"
    
    - name: Get VM Network Information
      community.vmware.vmware_drs_rule_info:
        cluster_name: 'R&D'
        validate_certs: False
        gather_network_info: yes
      register: vm_net

    - name: Debug Mac Address
      debug:
        var: item.virtual_machines[0].mac_address[0]
      with_items: "{{ vm_info.results }}"
    
    - name: Print VLAN information
      debug:
        var: vm_net.networks

    #- name: Changing network adapter
     # community.vmware.vmware_guest_network:
     #   cluster: "{{ item.virtual_machines[0].cluster }}"
     #   validate_certs: no
       # name: "{{ item.item }}"
       # mac_address: "{{ item.virtual_machines[0].mac_address[0] }}"
       # network_name: 'VLAN 1000'
      #  state: present
     # with_items: "{{ vm_info.results }}"

