---
- name: Check VMware VM Configuration
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Gather VM Information
      block:
        - community.vmware.vmware_vm_info:
            validate_certs: no
            vm_name: "{{ item }}"
          register: vm_info
          tags:
            - opa
        - name: Changing network adapter
          community.vmware.vmware_guest_network:
            cluster: "{{ vm_info.results[0].virtual_machines[0].cluster }}"
            validate_certs: no
            name: "{{ item }}"
            mac_address: "{{ vm_info.results[0].virtual_machines[0].mac_address[0] }}"
            network_name: 'VLAN 1000'
            state: present
          with_items: "{{ server.split(',') }}"
      loop: "{{ server.split(',') }}"
